class TermoLocationData {
  const TermoLocationData._();

  static const List<String> allCities = [
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkâri',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kilis',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak',
  ];

  static const List<String> detailedMetroCities = [
    'İstanbul',
    'Ankara',
    'İzmir',
    'Bursa',
    'Kocaeli',
    'Tekirdağ',
    'Antalya',
    'Adana',
    'Gaziantep',
  ];

  static const List<String> coastalCities = [
    'Adana',
    'Antalya',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Çanakkale',
    'Düzce',
    'Edirne',
    'Giresun',
    'Hatay',
    'İstanbul',
    'İzmir',
    'Kırklareli',
    'Kocaeli',
    'Mersin',
    'Muğla',
    'Ordu',
    'Rize',
    'Sakarya',
    'Samsun',
    'Sinop',
    'Tekirdağ',
    'Trabzon',
    'Yalova',
    'Zonguldak',
  ];

  static const List<String> inlandRegionOptions = [
    'Merkez',
    'Ara Bölge',
    'Yüksek Kesim',
  ];

  static const List<String> coastalRegionOptions = [
    'Kıyı Kesim',
    'İç Kesim',
    'Yüksek Kesim',
  ];

  static const Map<String, List<String>> metroDistricts = {
    'İstanbul': [
      'Adalar',
      'Arnavutköy',
      'Ataşehir',
      'Avcılar',
      'Bağcılar',
      'Bahçelievler',
      'Bakırköy',
      'Başakşehir',
      'Bayrampaşa',
      'Beşiktaş',
      'Beykoz',
      'Beylikdüzü',
      'Beyoğlu',
      'Büyükçekmece',
      'Çatalca',
      'Çekmeköy',
      'Esenler',
      'Esenyurt',
      'Eyüpsultan',
      'Fatih',
      'Gaziosmanpaşa',
      'Güngören',
      'Kadıköy',
      'Kağıthane',
      'Kartal',
      'Küçükçekmece',
      'Maltepe',
      'Pendik',
      'Sancaktepe',
      'Sarıyer',
      'Silivri',
      'Sultanbeyli',
      'Sultangazi',
      'Şile',
      'Şişli',
      'Tuzla',
      'Ümraniye',
      'Üsküdar',
      'Zeytinburnu',
    ],
    'Ankara': [
      'Akyurt',
      'Altındağ',
      'Ayaş',
      'Bala',
      'Beypazarı',
      'Çankaya',
      'Çubuk',
      'Elmadağ',
      'Etimesgut',
      'Gölbaşı',
      'Güdül',
      'Haymana',
      'Kahramankazan',
      'Keçiören',
      'Kızılcahamam',
      'Mamak',
      'Polatlı',
      'Pursaklar',
      'Sincan',
      'Yenimahalle',
    ],
    'İzmir': [
      'Aliağa',
      'Balçova',
      'Bayındır',
      'Bayraklı',
      'Bergama',
      'Bornova',
      'Buca',
      'Çeşme',
      'Dikili',
      'Foça',
      'Gaziemir',
      'Güzelbahçe',
      'Karabağlar',
      'Karaburun',
      'Karşıyaka',
      'Kemalpaşa',
      'Konak',
      'Menderes',
      'Menemen',
      'Narlıdere',
      'Ödemiş',
      'Seferihisar',
      'Selçuk',
      'Torbalı',
      'Urla',
    ],
    'Bursa': [
      'Gemlik',
      'Gürsu',
      'İnegöl',
      'İznik',
      'Karacabey',
      'Mudanya',
      'Mustafakemalpaşa',
      'Nilüfer',
      'Osmangazi',
      'Yıldırım',
    ],
    'Kocaeli': [
      'Başiskele',
      'Çayırova',
      'Darıca',
      'Derince',
      'Dilovası',
      'Gebze',
      'Gölcük',
      'İzmit',
      'Kandıra',
      'Karamürsel',
      'Kartepe',
      'Körfez',
    ],
    'Tekirdağ': [
      'Çerkezköy',
      'Çorlu',
      'Ergene',
      'Hayrabolu',
      'Kapaklı',
      'Malkara',
      'Marmaraereğlisi',
      'Muratlı',
      'Saray',
      'Süleymanpaşa',
      'Şarköy',
    ],
    'Antalya': [
      'Aksu',
      'Alanya',
      'Döşemealtı',
      'Kepez',
      'Konyaaltı',
      'Kumluca',
      'Manavgat',
      'Muratpaşa',
      'Serik',
    ],
    'Adana': [
      'Çukurova',
      'Kozan',
      'Sarıçam',
      'Seyhan',
      'Yumurtalık',
      'Yüreğir',
    ],
    'Gaziantep': [
      'Araban',
      'İslahiye',
      'Nizip',
      'Nurdağı',
      'Oğuzeli',
      'Şahinbey',
      'Şehitkamil',
    ],
  };

  static bool isMetropolitan(String city) {
    return detailedMetroCities.contains(city);
  }

  static bool isCoastal(String city) {
    return coastalCities.contains(city);
  }

  static List<String> locationOptionsForCity(String city) {
    if (isMetropolitan(city)) {
      return metroDistricts[city] ?? const [];
    }
    return isCoastal(city) ? coastalRegionOptions : inlandRegionOptions;
  }
}